mqtt:
  host: muffin.iot.home
  user: frigate
  password: fdJA0OQ8yA3C750V

ffmpeg:
  hwaccel_args: preset-nvidia

detectors:
  onnx:
    type: onnx

model:
  model_type: yolonas
  width: 320 # <--- should match whatever was set in notebook
  height: 320 # <--- should match whatever was set in notebook
  input_pixel_format: bgr
  input_tensor: nchw
  path: /config/yolo_nas_s.onnx
  labelmap_path: /labelmap/coco-80.txt

detect:
  enabled: true
  width: 1280
  height: 720

record:
  enabled: true

cameras:

  back_yard:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:Biodyne^518^@backyardcamera.iot.home:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

  front_entry:
    enabled: true
    ffmpeg:
      inputs:
        - path: 
            rtsp://admin:Biodyne^518^@frontentrycamera.iot.home:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    motion:
      mask: 0.908,0.209,0.927,0.021,0.996,0.016,0.986,0.243

version: 0.16-0
